services:
  - docker

branches:
  only:
    - master

before_install:
  - docker-compose build

before_script:
  - docker-compose run -T --rm -e RAILS_ENV=test zoo_stats bundle exec rake db:setup

script:
  - docker-compose run -T --rm -e RAILS_ENV=test zoo_stats bundle exec rspec
