language: ruby
rvm:
  - 2.5.1
sudo: false
services:
  - docker

before_install:
  - docker-compose pull
  - docker-compose build
  - docker ps

install:
  - docker-compose run -T --rm -e RAILS_ENV=test --entrypoint="bundle install" zoo_stats

after_install:
  # setup testing db
  - docker-compose run -T --rm -e RAILS_ENV=test --entrypoint="bundle exec rake db:setup" zoo_stats

script:
  - docker-compose run -T --rm -e RAILS_ENV=test --entrypoint="bundle exec rspec" zoo_stats
