default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: zoo_stats
  password: zoo_stats
  port: 5432

development:
  <<: *default
  database: zoo_stats_development

test:
  <<: *default
  database: zoo_stats_test

staging:
  url: <%= Rails.application.credentials.database_url_staging %>

production:
  url: <%= Rails.application.credentials.database_url_production %>
