apiVersion: v1
data:
  nginx.conf: |+
    upstream app {
      server zoo-event-stats-grafana-app:3000;
    }

    server {
      access_log /dev/stdout main;
      error_log /dev/stdout;
      auth_basic "Restricted Area";
      auth_basic_user_file /etc/nginx/.htpasswd;

      location / {
        proxy_pass http://app;
        proxy_set_header Authorization "";
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: zoo-event-stats-grafana-nginx-config